### PR TITLE
[fix] Refactor Homepage Class To Functional

### LINKED ISSUE #54: [fix] Covert Homepage Component From Class based to Functional based

### PR DESCRIPTION
**Pull request by nitishmittal1990**
# Description
- Refactored Homepage Component from Class to Functional.
- Updated Test Cases Accordingly 

Closes: #54 

## Desktop View:
Screenshot 2020-02-22 at 3 20 06 PM

## Mobile View:

Screenshot 2020-02-22 at 3 20 26 PM

### CODE REVIEW

**Review by vineetvk01 — APPROVED** [review]
lgtm

File: client/src/views/Homepage/index.js [hunk 1]
```diff
@@ -1,98 +1,87 @@
...
-            </Button>
-          </div>
-        </Grid>
-      </section>
-    );
-  }
-}
+  return (
+    <section className={style.searchContainer}>
+      <Grid
```
Comment (fenilgandhi) [inline client/src/views/Homepage/index.js:42]: We can also use CSS based Flexbox

**Review by fenilgandhi — APPROVED** [review]

File: client/src/views/Homepage/index.js (hunk 1 above)
Comment (nitishmittal1990) [reply client/src/views/Homepage/index.js:42]: Will refactor later
